services:
  - type: web
    name: payment-service
    env: java
    buildCommand: ./gradlew build -x test
    startCommand: java -jar build/libs/payment-service-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: cloud
      - key: PORT
        value: 8090
    healthCheckPath: /api/config

databases:
  - name: payment-service-db
    plan: free
    databaseName: paymentdb
    user: paymentuser

